all: main.o changevowel.o deletefour.o findtobe.o readprinttext.o sortlast.o
	gcc main.o changevowel.o deletefour.o findtobe.o readprinttext.o sortlast.o -o prog

main.o: main.c changevowel.h deletefour.h findtobe.h readprinttext.h sortlast.h
	gcc -c main.c

changevowel.o: changevowel.c changevowel.h
	gcc -c changevowel.c

deletefour.o: deletefour.c deletefour.h
	gcc -c deletefour.c

findtobe.o: findtobe.c findtobe.h
	gcc -c multi_between_negative.c

readprinttext.o: readprinttext.c readprinttext.h
	gcc -c readprinttext.c

sortlast.o: sortlast.c sortlast.h
	gcc -c sortlast.c

clear:
	rm -rf *.o

assemble:
	./prog && a.out